export const legacystudentlist:any[]=[
  {
    StudentName: "sakthivel.s",
    year: "CSE 3Rd year ",
    collegeName: "Sethu institute of technology ",
    Email: "sakthivelsekar03@Gmail.com",
    MobileNo: 8838185633,
    Gender: "Male",
    Accomodation: "Yes",
    SYMPHONIQUE: " ",
    விவாத: " ",
    DIVIDE: " ",
    MONSTERS: " ",
    MARTIAL: " ",
    KALAKKAL: " ",
    SHERLOCK: " ",
    QUIZZARDS: " ",
    BEST: " ",
    RANGOLI: " ",
    GRAPHIX: " ",
    CHOREO: " ",
    VOICE: " ",
    MUSIC: " ",
    DIVINE: " ",
    MARKETOMANIA: " ",
    கவித்திடல்: " ",
    PIXIE: " ",
    DRAMATICS: " ",
    CINEMATRIX: " ",
    LIPHOMANIAC: " ",
    YOGA: " ",
     DEBATE: " ",
     EXPRESSIONS: " ",
     TREASURE: " ",
     MAKE: "TRUE",
     EXTEMPORE: " ",
    WAR: " ",
    மறுவார்த்தை: " ",
    PENCIL: " ",
    LYRICAL: " "
   },
   {
    StudentName: "S PEVEENA SRI",
    year: "2nd YEAR BIOMEDICAL",
    collegeName: "SETHU INTITUTE OF TECHNOLOGY",
    Email: "peveenasri27@gmail.com",
    MobileNo: 9361231636,
    Gender: "Female",
    Accomodation: "No",
    SYMPHONIQUE: " ",
    விவாத: " ",
    DIVIDE: " ",
    MONSTERS: " ",
    MARTIAL: " ",
    KALAKKAL: " ",
    SHERLOCK: " ",
    QUIZZARDS: " ",
    BEST: " ",
    RANGOLI: " ",
    GRAPHIX: " ",
    CHOREO: " ",
    VOICE: " ",
    MUSIC: " ",
    DIVINE: " ",
    MARKETOMANIA: " ",
    கவித்திடல்: " ",
    PIXIE: " ",
    DRAMATICS: " ",
    CINEMATRIX: " ",
    LIPHOMANIAC: " ",
    YOGA: " ",
     DEBATE: " ",
     EXPRESSIONS: " ",
     TREASURE: " ",
     MAKE: "TRUE",
     EXTEMPORE: " ",
    WAR: " ",
    மறுவார்த்தை: " ",
    PENCIL: " ",
    LYRICAL: " "
   },
   {
    StudentName: "VIGNESHWARAN K ",
    year: "2ND DEPARTMENT OF MECHANICAL  ",
    collegeName: "SETHU INSTITUTE OF TECHNOLOGY ",
    Email: "pettavicky2003@gmail.com",
    MobileNo: 6384250254,
    Gender: "Male",
    Accomodation: "No",
    SYMPHONIQUE: " ",
    விவாத: " ",
    DIVIDE: " ",
    MONSTERS: " ",
    MARTIAL: " ",
    KALAKKAL: " ",
    SHERLOCK: " ",
    QUIZZARDS: " ",
    BEST: " ",
    RANGOLI: "TRUE",
    GRAPHIX: " ",
    CHOREO: " ",
    VOICE: "TRUE",
    MUSIC: " ",
    DIVINE: " ",
    MARKETOMANIA: " ",
    கவித்திடல்: "TRUE",
    PIXIE: " ",
    DRAMATICS: " ",
    CINEMATRIX: "TRUE",
    LIPHOMANIAC: " ",
    YOGA: " ",
     DEBATE: "TRUE",
     EXPRESSIONS: " ",
     TREASURE: " ",
     MAKE: " ",
     EXTEMPORE: " ",
    WAR: " ",
    மறுவார்த்தை: " ",
    PENCIL: " ",
    LYRICAL: " "
   },
   {
    StudentName: "THIRISHA B",
    year: "2ND DEPARTMENT OF MECHANICAL ",
    collegeName: "SETHU INSTITUTE OF TECHNOLOGY ",
    Email: "bthirsha4@gmail.com",
    MobileNo: 7904855693,
    Gender: "Female",
    Accomodation: "No",
    SYMPHONIQUE: " ",
    விவாத: " ",
    DIVIDE: " ",
    MONSTERS: " ",
    MARTIAL: " ",
    KALAKKAL: " ",
    SHERLOCK: " ",
    QUIZZARDS: " ",
    BEST: " ",
    RANGOLI: "TRUE",
    GRAPHIX: " ",
    CHOREO: " ",
    VOICE: " ",
    MUSIC: " ",
    DIVINE: " ",
    MARKETOMANIA: " ",
    கவித்திடல்: "TRUE",
    PIXIE: " ",
    DRAMATICS: " ",
    CINEMATRIX: " ",
    LIPHOMANIAC: " ",
    YOGA: " ",
     DEBATE: "TRUE",
     EXPRESSIONS: " ",
     TREASURE: " ",
     MAKE: " ",
     EXTEMPORE: " ",
    WAR: " ",
    மறுவார்த்தை: " ",
    PENCIL: "TRUE",
    LYRICAL: " "
   },
   {
    StudentName: "THANGADURAI M",
    year: "2ND DEPARTMENT OF MECHANICAL ",
    collegeName: "SETHU INSTITUTE OF TECHNOLOGY ",
    Email: "mstduraii@gmail.com",
    MobileNo: 6380889390,
    Gender: "Male",
    Accomodation: "No",
    SYMPHONIQUE: " ",
    விவாத: " ",
    DIVIDE: " ",
    MONSTERS: " ",
    MARTIAL: " ",
    KALAKKAL: " ",
    SHERLOCK: "TRUE",
    QUIZZARDS: " ",
    BEST: " ",
    RANGOLI: " ",
    GRAPHIX: " ",
    CHOREO: " ",
    VOICE: " ",
    MUSIC: " ",
    DIVINE: " ",
    MARKETOMANIA: " ",
    கவித்திடல்: "TRUE",
    PIXIE: " ",
    DRAMATICS: " ",
    CINEMATRIX: " ",
    LIPHOMANIAC: " ",
    YOGA: " ",
     DEBATE: " ",
     EXPRESSIONS: " ",
     TREASURE: "TRUE",
     MAKE: " ",
     EXTEMPORE: " ",
    WAR: "TRUE",
    மறுவார்த்தை: " ",
    PENCIL: " ",
    LYRICAL: "TRUE"
   },
   {
    StudentName: "SANJAY HARSHAN P",
    year: "2ND DEPARTMENT OF MECHANICAL",
    collegeName: "SETHU INSTITUTE OF TECHNOLOGY ",
    Email: "sanjayharshan15@gmail.com",
    MobileNo: 9342750540,
    Gender: "Male",
    Accomodation: "No",
    SYMPHONIQUE: " ",
    விவாத: " ",
    DIVIDE: " ",
    MONSTERS: " ",
    MARTIAL: " ",
    SHERLOCK: "TRUE",
    QUIZZARDS: " ",
    BEST: " ",
    RANGOLI: " ",
    GRAPHIX: " ",
    CHOREO: " ",
    VOICE: " ",
    MUSIC: " ",
    DIVINE: " ",
    MARKETOMANIA: " ",
    கவித்திடல்: " ",
    PIXIE: " ",
    DRAMATICS: " ",
    CINEMATRIX: " ",
    LIPHOMANIAC: " ",
    YOGA: " ",
     DEBATE: " ",
     EXPRESSIONS: " ",
     TREASURE: "TRUE",
     MAKE: " ",
     EXTEMPORE: " ",
    WAR: " ",
    மறுவார்த்தை: " ",
    PENCIL: " ",
    LYRICAL: "TRUE"
   },
   {
    StudentName: "SANJEEV HARSHAN P",
    year: "2ND DEPARTMENT OF MECHANICAL",
    collegeName: "SETHU INSTITUTE OF TECHNOLOGY ",
    Email: "sanjeevharshan1510@gmail.com",
    MobileNo: 6374413049,
    Gender: "Male",
    Accomodation: "No",
    SYMPHONIQUE: " ",
    விவாத: " ",
    DIVIDE: " ",
    MONSTERS: " ",
    MARTIAL: " ",
    KALAKKAL: " ",
    SHERLOCK: "TRUE",
    QUIZZARDS: " ",
    BEST: " ",
    RANGOLI: " ",
    GRAPHIX: " ",
    CHOREO: " ",
    VOICE: " ",
    MUSIC: " ",
    DIVINE: " ",
    MARKETOMANIA: " ",
    கவித்திடல்: " ",
    PIXIE: " ",
    DRAMATICS: " ",
    CINEMATRIX: " ",
    LIPHOMANIAC: " ",
    YOGA: " ",
     DEBATE: " ",
     EXPRESSIONS: " ",
     TREASURE: "TRUE",
     MAKE: " ",
     EXTEMPORE: " ",
    WAR: " ",
    மறுவார்த்தை: " ",
    PENCIL: " ",
    LYRICAL: "TRUE"
   },
   {
    StudentName: "SABAREESH S V",
    year: "2ND DEPARTMENT OF MECHANICAL",
    collegeName: "SETHU INSTITUTE OF TECHNOLOGY ",
    Email: "sabareesh2775@gmail.com",
    MobileNo: 9865976844,
    Gender: "Male",
    Accomodation: "No",
    SYMPHONIQUE: " ",
    விவாத: " ",
    DIVIDE: " ",
    MONSTERS: " ",
    MARTIAL: " ",
    KALAKKAL: " ",
    SHERLOCK: "TRUE",
    QUIZZARDS: " ",
    BEST: " ",
    RANGOLI: " ",
    GRAPHIX: " ",
    CHOREO: " ",
    VOICE: " ",
    MUSIC: " ",
    DIVINE: " ",
    MARKETOMANIA: " ",
    கவித்திடல்: " ",
    PIXIE: " ",
    DRAMATICS: " ",
    CINEMATRIX: " ",
    LIPHOMANIAC: " ",
    YOGA: " ",
     DEBATE: " ",
     EXPRESSIONS: " ",
     TREASURE: "TRUE",
     MAKE: " ",
     EXTEMPORE: " ",
    WAR: " ",
    மறுவார்த்தை: " ",
    PENCIL: " ",
    LYRICAL: " "
   },
   {
    StudentName: "NIRMAL BABU K S",
    year: "2ND DEPARTMENT OF MECHANICAL",
    collegeName: "SETHU INSTITUTE OF TECHNOLOGY ",
    Email: "vknirmalbabu@gmail.com",
    MobileNo: 8667622242,
    Gender: "Male",
    Accomodation: "No",
    SYMPHONIQUE: " ",
    விவாத: " ",
    DIVIDE: " ",
    MONSTERS: " ",
    MARTIAL: " ",
    KALAKKAL: " ",
    SHERLOCK: " ",
    QUIZZARDS: " ",
    BEST: " ",
    RANGOLI: "TRUE",
    GRAPHIX: " ",
    CHOREO: " ",
    VOICE: " ",
    MUSIC: " ",
    DIVINE: " ",
    MARKETOMANIA: " ",
    கவித்திடல்: " ",
    PIXIE: " ",
    DRAMATICS: " ",
    CINEMATRIX: " ",
    LIPHOMANIAC: " ",
    YOGA: " ",
     DEBATE: "TRUE",
     EXPRESSIONS: " ",
     TREASURE: "TRUE",
     MAKE: " ",
     EXTEMPORE: " ",
    WAR: "TRUE",
    மறுவார்த்தை: " ",
    PENCIL: " ",
    LYRICAL: " "
   }
  ]