import { Student } from "./models/students.model";

export const studentlist:Student[]=[ {
    id:'',
    name:'Organizers',
    email:'organizers@gmail.com',
    password:'organizers@ecc',
    isAdmin :false,
    event:[],
    yourteams:[],
    admissionNo:10001,
    gender:'Male',
    department:'CSE',
    year:'IV',
    section:'B',
    points:0
  },{
      id:'',
      name:'Pramanayagam T',
      email:'karthick4043677_cs@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:16465,
      gender:'Male',
      department:'CSE',
      year:'IV',
      section:'B',
      points:0
    },
    {
      id:'',
      name:'Deepak V J',
      email:'jayachitra143_cs@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:16812,
      gender:'Male',
      department:'CSE',
      year:'IV',
      section:'B',
      points:0
    },
    {
      id:'',
      name:'Jousha Joel J',
      email:'joshuajoel023_cs@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:16928,
      gender:'Male',
      department:'CSE',
      year:'IV',
      section:'B',
      points:0
    },
    {
      id:'',
      name:'Pruthvi Raj M',
      email:'pruthvimathavan_cs@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:16948,
      gender:'Male',
      department:'CSE',
      year:'IV',
      section:'B',
      points:0
    },{
      id:'',
      name:'Namasivaayam L',
      email:'Namasivaayam@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:16712,
      gender:'Male',
      department:'AIDS',
      year:'IV',
      section:'B',
      points:0
    },{
      id:'',
      name:'Gowshi K',
      email:'Gowshi@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:16606,
      gender:'Male',
      department:'MECH',
      year:'IV',
      section:'B',
      points:0
    },{
      id:'',
      name:'Naboth Demetrius R ',
      email:'Naboth@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:17705,
      gender:'Male',
      department:'AIDS',
      year:'III',
      section:'B',
      points:0
    },{
      id:'',
      name:'Sherwyn Titus ',
      email:'Sherwyn@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:16802,
      gender:'Male',
      department:'CSE',
      year:'IV',
      section:'C',
      points:0
    },{
      id:'',
      name:'Jayajith Roshan S ',
      email:'Jayajith@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:16468,
      gender:'Male',
      department:'CSE',
      year:'IV',
      section:'B',
      points:0
    },{
      id:'',
      name:'Viruthika M',
      email:'Viruthika@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:16932,
      gender:'Female',
      department:'IT',
      year:'IV',
      section:'B',
      points:0
    },{
      id:'',
      name:'Vijeta T',
      email:'Vijeta@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:16764,
      gender:'Female',
      department:'CSE',
      year:'IV',
      section:'B',
      points:0
    },
    {
      id:'',
      name:'Logeshwari C',
      email:'Logeshwari@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:16658,
      gender:'Female',
      department:'CSE',
      year:'IV',
      section:'C',
      points:0
    },{
      id:'',
      name:'Trilok Guru T R',
      email:'Trilok@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:16860,
      gender:'Male',
      department:'CSE',
      year:'IV',
      section:'A',
      points:0
    },{
      id:'',
      name:'Aakash T',
      email:'Aakash@mepcoeng.ac.in',
      password:'',
      isAdmin :false,
      event:[],
      yourteams:[],
      admissionNo:17110,
      gender:'Male',
      department:'CSE',
      year:'IV',
      section:'A',
      points:0
    },
]